### ISSUE TITLE
源码中可能错误调用了Fresco的方法

### ISSUE THREAD

**Issue by cocowobo** [hpdx/fresco-helper#15]
1,没事看您的源码的时候，看到这里com.facebook.fresco.helper.ImageLoader#loadLocalDiskCache
2.方法是【从本地缓存文件中获取Bitmap】里面调用了com.facebook.imagepipeline.core.ImagePipeline#fetchDecodedImage(ImageRequest imageRequest,
      Object callerContext)方法，第二个参数我看您的使用和命名可以肯定应该是 上下文对象，您却将第二个参数传入了 ImageRequest.RequestLevel.DISK_CACHE，这个应该是第三个参数，第二个参数的context上下文是不应该省略的，您或许是手误了吗？
3.我也看了好几天fresco了，如果提的这问题是我的知识浅薄。麻烦您关一下，

**Comment by hpdx** [comment]
这个地方是我疏忽了，调错方法了
`
public DataSource<CloseableReference<CloseableImage>> fetchDecodedImage(
      ImageRequest imageRequest,
      Object callerContext) {
    return fetchDecodedImage(imageRequest, callerContext, ImageRequest.RequestLevel.FULL_FETCH);
  }
`

应该调用下面这个方法

`
public DataSource<CloseableReference<CloseableImage>> fetchDecodedImage(
      ImageRequest imageRequest,
      Object callerContext,
      ImageRequest.RequestLevel lowestPermittedRequestLevelOnSubmit) {
    return fetchDecodedImage(
        imageRequest, callerContext, lowestPermittedRequestLevelOnSubmit, null);
  }
`
