### ISSUE TITLE
2.1.7版本依赖的 fresco 版本还是1.11.0，并没有升级到1.13.0啊

### ISSUE THREAD

**Issue by HeyAragon** [hpdx/fresco-helper#17]
2.1.7版本依赖的 fresco 版本还是1.11.0，并没有升级到1.13.0啊

**Comment by hpdx** [comment]
@HeyAragon 
      之前上传到maven总是失败，后来忘记试了，感谢提醒啊。
刚又试了一遍，上传成功了。你试试这个 `compile 'com.facebook.fresco.helper:fresco-helper:2.1.8'`

**Comment by HeyAragon** [comment]
可以了~！多谢
