### ISSUE TITLE
图片如果加载失败，此时图片如果设置了点击事件，就无法点击跳转页面了

### ISSUE THREAD

**Issue by zhuoshirong** [hpdx/fresco-helper#19]
图片如果加载失败，此时图片如果设置了点击事件，就无法点击跳转页面了，请问有什么办法可以设置如果图片加载失败，图片点击事件有效，可以正常跳转另一个界面

**Comment by hpdx** [comment]
@zhuoshirong 

可以考虑下面的设置，任意一种都可以，一般使用占位图
1、占位图
app:placeholderImage="@mipmap/ic_launcher"
app:placeholderImageScaleType="centerCrop"

2、加载失败时，显示的图
app:failureImage="@mipmap/ic_launcher"
app:failureImageScaleType="centerInside"

3、加载失败后，重试显示的图
app:retryImage="@mipmap/ic_launcher"
app:retryImageScaleType="centerCrop"

**Comment by zhuoshirong** [comment]
大佬，不是这个意思，是图片加载失败点击事件冲突了，比如： 图片是头像点击事件是跳转另一个activity页面，这时如果图片地址是个错误的地址，或者图片加载失败时，这时原本设置的点击事件就无效了，点击无法跳转另一个activity页面

**Comment by hpdx** [comment]
@zhuoshirong 
你好，
     这个问题我明白怎么回事了，解决办法有两种：
1、禁用加载失败重试的点击事件：
setTapToRetryEnabled(false) // 禁用点击重试功能

` SimpleDraweeView simpleDraweeView = null;
        Uri uri = Uri.parse(url);
        GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(context.getResources())
                .setPlaceholderImage(defaultResource)//默认图
                .setFailureImage(defaultResource)//加载失败
                .setPlaceholderImageScaleType(ScalingUtils.ScaleType.CENTER_CROP)
                .setActualImageScaleType(ScalingUtils.ScaleType.CENTER_CROP)
                .build();

        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setTapToRetryEnabled(false) // 禁用点击重试功能
                .setOldController(simpleDraweeView.getController())
                .build();

        simpleDraweeView.setHierarchy(hierarchy);
        simpleDraweeView.setController(controller);`

2、在外层包一个ViewGroup，SimpleDraweeView禁用点击事件，事件由fl_avatar来处理，具体如下：
`
  <FrameLayout
        android:id="@+id/fl_avatar"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

        <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/sdv_avatar"
            android:layout_width="180dp"
            android:layout_height="180dp"
            android:clickable="false"
            app:actualImageScaleType="centerCrop"
            app:placeholderImage="@drawable/logo_540"
            app:placeholderImageScaleType="centerCrop"/>

    </FrameLayout>
`

**Comment by zhuoshirong** [comment]
第2个方法我早试过了不行，要点很多次才行，这种包起来的方式不行；
第1种方法：
   // 从网络加载一张图片
        LinearLayout linear_sdv1 = this.findViewById(R.id.linear_sdv1);
        SimpleDraweeView simpleDraweeView = this.findViewById(R.id.sdv_1);
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setTapToRetryEnabled(false) // 禁用点击重试功能
                .setOldController(simpleDraweeView.getController())
                .build();
        simpleDraweeView.setController(controller);
        // 模拟加载失败
        Phoenix.with(simpleDraweeView).load(url + "21321321321");
        simpleDraweeView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.e("TAGG","点击事件");
                Intent intent = new Intent(FrescoBaseUseActivity.this, GifActivity.class);
                startActivity(intent);
            }
        });
这样我也试过了用你的DEMO，结果还是不行，要点击很多次；群主最好自己试一下，大概问题就是图片点击事件拦截了
