### ISSUE TITLE
图片如果加载失败，此时图片如果设置了点击事件，就无法点击跳转页面了

### ISSUE THREAD

**Issue by zhuoshirong** [hpdx/fresco-helper#20]
第2个方法我早试过了不行，用linearlayout framelayout包起来的方式不行, 要点很多次才行，

第1种方法：
//从网络加载一张图片
LinearLayout linear_sdv1 = this.findViewById（R.id.linear_sdv1 ）; 
SimpleDraweeView simpleDraweeView = this.findViewById（R.id.sdv_1）; 
DraweeController controller = Fresco.newDraweeControllerBuilder（）。
setTapToRetryEnabled（false）//禁用点击重试功能
.setOldController（simpleDraweeView.getController（））。build 
（）; 
simpleDraweeView.setController（控制器）; 
//模拟加载失败
Phoenix.with（simpleDraweeView）.load（url +“21321321321”）; 
simpleDraweeView.setOnClickListener（new View.OnClickListener（）{ 
@ override
public void onClick（View v）{ 
Log.e（“TAGG”，“点击事件”）;
Intent intent = new Intent（FrescoBaseUseActivity.this，GifActivity.class）; 
startActivity（意向）; 
} 
};; 
这样我也试过了用你的DEMO，结果还是不行，要点击很多次;群主最好自己试一下，大概问题就是图片点击事件拦截了

**Comment by hpdx** [comment]
@zhuoshirong 
1、你上面的测试代码写的有问题，先是禁用了加载失败点击重试功能，后面使用Phoenix.with（simpleDraweeView）.load（url +“21321321321”）;
Phoenix这个库里面默认是开启加载失败点击重试功能的。后面我考虑默认把这个关掉

2、你就使用下面的代码，再试试。
```
 SimpleDraweeView simpleDraweeView = null;
        Uri uri = Uri.parse(url);
        GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(context.getResources())
                .setPlaceholderImage(defaultResource)//默认图
                .setFailureImage(defaultResource)//加载失败
                .setPlaceholderImageScaleType(ScalingUtils.ScaleType.CENTER_CROP)
                .setActualImageScaleType(ScalingUtils.ScaleType.CENTER_CROP)
                .build();

        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setTapToRetryEnabled(false) // 禁用点击重试功能
                .setOldController(simpleDraweeView.getController())
                .build();

        simpleDraweeView.setHierarchy(hierarchy);
        simpleDraweeView.setController(controller);
```

**Comment by hpdx** [comment]
@zhuoshirong 
你可以试试这个版本：implementation 'com.facebook.fresco.helper:fresco-helper:2.2.0'

若是不想使用AndroidX，那你只能下载v.2.1.8的源码自己修改了，ImageLoader里的
```
  public static void loadImage(SimpleDraweeView simpleDraweeView,
                                 Uri uri,
                                 final int reqWidth,
                                 final int reqHeight,
                                 BasePostprocessor postprocessor,
                                 ControllerListener<ImageInfo> controllerListener,
                                 boolean isSmall) {}
```
这个方法，修改draweeControllerBuilder.setTapToRetryEnabled(false); 将true改为false

哥们，只能帮你到这里了。
