### ISSUE TITLE
有一个写死的Toast

### ISSUE THREAD

**Issue by chenyue404** [hpdx/fresco-helper#23]
fresco-helper/src/main/java/com/facebook/fresco/helper/Phoenix.java
506行，有一个写死的toast，对多语言很不友好。
可以不弹，或者改成资源文件让开发者覆盖，或者弄一个回调？

**Comment by hpdx** [comment]
@chenyue404  
你好，
       这个Toast正常情况下是不会弹出来的，出现的目的是提醒开发者，这个API没用对。
       不过你说的也有道理，也有可能在一些特殊情况下回显示给用户看，因此，已作出修改。
