### ISSUE TITLE
ppvProgressFillType 与其他第三方库冲突了 能否修改一下字段

### ISSUE THREAD

**Issue by zhucb** [hpdx/fresco-helper#25]
<attr name="ppvProgressFillType" format="enum" >
            <enum name="radial" value="0"/>
            <enum name="center" value="1"/>
        </attr>

谢谢

**Comment by hpdx** [comment]
这个问题最好的处理办法就是拿到源码，自己改。
原因：比如我把属性前缀改成ff，` <attr name="ffProgressFillType" format="enum" >` 过两天又有人说ffProgressFillType这个冲突了，我改还是？
