### ISSUE TITLE
可以考虑加上一个自定义key 缓存图片

### ISSUE THREAD

**Issue by guoshilun** [hpdx/fresco-helper#26]
金山云图片地址是每次访问时间戳都不一样，图片地址也不一样

**Comment by hpdx** [comment]
“加上一个自定义key 缓存图片”，目前常用的图片加载框架Glide、Fresco、Coil，一张图片的唯一标识就是访问图片资源的url。

1、要是同一张图片的url老是变，这个应该是对象存储商那边的问题，你给他们反馈下。我用过七牛云、阿里云、腾讯云的，同一资源的访问url都是固定的。

2、"金山云图片地址是每次访问时间戳都不一样，图片地址也不一样"，针对这个问题：
添加自定义key 缓存图片，这个具体你想去做？我们沟通下
