### ISSUE TITLE
仓库用不了了

### ISSUE THREAD

**Issue by zeason0124** [hpdx/fresco-helper#29]
Bintray 和 Jcenter 仓库关闭了，能否换下仓库，谢谢 https://my.oschina.net/cubacn/blog/5025716

**Comment by zeason0124** [comment]
https://my.oschina.net/cubacn/blog/5025716

**Comment by hpdx** [comment]
已发布到jitpack上了，`implementation 'com.github.hpdx:fresco-helper:2.5.0'`
