### ISSUE TITLE
 找不到url 怎么弄？

### ISSUE THREAD

**Issue by 836986836** [hpdx/fresco-helper#3]
<com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/sdv_1"
                android:layout_width="90dp"
                android:layout_height="90dp"
                app:actualImageScaleType="centerCrop"
                app:url="@{url}" />

Error:(23) No resource identifier found for attribute 'url' in package 'cn.com.xxx.xxx'
    Error:(30) No resource identifier found for attribute 'url' in package 'cn.com.xxx.xxx'
    Error:(39) No resource identifier found for attribute 'url' in package 'cn.com.xxx.xxx'
    Error:(50) No resource identifier found for attribute 'url' in package 'cn.com.xxx.xxx'
    Error:(60) No resource identifier found for attribute 'url' in package 'cn.com.xxx.xxx'
    Error:(74) No resource identifier found for attribute 'url' in package 'cn.com.xxx.xxx'

**Comment by hpdx** [comment]
需要使用dataBinding 
 @BindingAdapter({"url"})
    public static void loadImage(SimpleDraweeView simpleDraweeView, String url) {
        Phoenix.with(simpleDraweeView).load(url);
    }
