### ISSUE TITLE
显示从网络加载照片墙

### ISSUE THREAD

**Issue by pudao2010** [hpdx/fresco-helper#5]
这个被砍掉了？
我想了解的是列表类型的控件如RecyclerView，去加载图片，图片量很大，且带有加载详图（并且可以缩放）的功能
快速滑动时如何优化？
使用Fresco加载时如何控制内存，列表型控件图片很多
内存持续增加会导致OOM，如何去回收内存？

**Comment by hpdx** [comment]
拆分成新的库了，地址：https://github.com/hpdx/fresco-photoview
