### ISSUE TITLE
不支持保存gif

### ISSUE THREAD

**Issue by 70kg** [hpdx/fresco-helper#6]
A哥，这个库不支持保存GIF图片到本地吧

**Comment by hpdx** [comment]
@70kg 没试过，我回头试试。

**Comment by hpdx** [comment]
@70kg 可以保存gif图片到本地的，代码如下：
`
  public void downloadImageGif(Context context) {
        String url = "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1496383829892&di=ac88e62a1424eaddcc03502e99e8168f&imgtype=0&src=http%3A%2F%2Fi3.17173cdn.com%2F2fhnvk%2FYWxqaGBf%2Fcms3%2FVqLgYAbkkbmrjhy.gif";
        String filePath = FileUtils.getImageDownloadPath(context, url);
        Phoenix.with(context)
                .setUrl(url)
                .setResult(new IDownloadResult(filePath) {
                    @Override
                    public void onResult(String filePath) {
                        MLog.i("filePath = " + filePath);

                    }
                })
                .download();
    }
`

**Comment by 70kg** [comment]
A哥厉害，我眼花了
