### ISSUE TITLE
图片加载失败会导致点击事件不响应

### ISSUE THREAD

**Issue by 460545614** [hpdx/fresco-helper#9]
1. 若设置不可用url或resid，总之加载失败回导致图片设置的点击事件或者recycleview项的点击事件也无法响应，会在连续点击四五次后才开始响应，我在你的demo源码中也验证了这个问题
2.页面加载多图时，连续滑动页面会导致部分图片变黑
3.页面不停的加载时，会导致oom导致dump

**Comment by hpdx** [comment]
@460545614 你反馈的问题2和3，我亲自测过Fresco v1.4.0这个版本，加载本地相册3000多张图片（对，你没看错是3000多张），网络图片也测了10张左右，反复滚动，没有出现你所说的部分图片变黑（你那边可能图片本身有问题吧），不停滚动会导致OOM的问题。
你可以拿我开源的这个库，试试看：[https://github.com/hpdx/fresco-photoview](https://github.com/hpdx/fresco-photoview)

我们公司的几个产品目前也在使用我开源的这个库，用户量千万级别（美丽约），目前也没出现过你所反馈的问题。我猜测可能是你自己使用的问题，你再仔细检查下看。至于问题1，与图片加载库应该是没关系的，应该还是你用的问题。

**Comment by hpdx** [comment]
@460545614 至于使用Fresco会导致OOM吗？我的答案是会的，那是在你使用不当的时候，比如各种配置没配对等。

**Comment by hpdx** [comment]
@460545614 对了，你若想深入了解Fresco，可以看我写的这篇文章：[http://blog.csdn.net/android_ls/article/details/53137867](http://blog.csdn.net/android_ls/article/details/53137867)

**Comment by 460545614** [comment]
1.第一种情况我也验证几种方式 ，其他方式响应是正常的 2第二种在华为emui4.0.2、oppo机型出现 第三种日志确实报的fresco，也可能不是库的原因；至于使用上问题可能性不大..

**Comment by 460545614** [comment]
我也只是把遇到的问题反馈下，没别的意思

**Comment by hpdx** [comment]
@460545614 我想你可能是刚开始使用Fresco这个库，可能会遇到比别人多的问题，我也只是告诉你我实践过的一些结论。我们有没有利益冲突，我干嘛呀，🙄
